spring:
  datasource:
    username: platform
    password: FYTIUfuytftyu5r4R^
    url: jdbc:mysql://mysql-81c187e1e9a8-public.rds.volces.com/config?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:com/data/mapper/**/*Mapper.xml
  type-aliases-package: com.data.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl